version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:30"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 8
    ignore:
      - dependency-name: typescript
        update-types:
          - version-update:semver-minor
          - version-update:semver-major
    groups:
      production-minor-and-patch:
        applies-to: version-updates
        dependency-type: production
        update-types:
          - minor
          - patch
      development-minor-and-patch:
        applies-to: version-updates
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:30"
      timezone: America/Sao_Paulo
